import { sqliteTable, text, integer, primaryKey, index, uniqueIndex } from "drizzle-orm/sqlite-core";
export const catalog = sqliteTable("commerce_products", {
 owner:text("owner").notNull(),store:text("store").notNull(),id:text("id").notNull(),sku:text("sku").notNull(),name:text("name").notNull(),brand:text("brand").notNull(),category:text("category").notNull(),priceCents:integer("price_cents").notNull(),stock:integer("stock").notNull(),image:text("image").notNull(),description:text("description").notNull(),published:integer("published").notNull().default(1),
 erpVersion:integer("erp_version").notNull().default(-1),
},t=>[primaryKey({columns:[t.owner,t.store,t.id]}),uniqueIndex("commerce_product_sku").on(t.owner,t.store,t.sku)]);
export const orders=sqliteTable("commerce_orders",{
 id:text("id").primaryKey(),owner:text("owner").notNull(),store:text("store").notNull(),idempotency:text("idempotency").notNull(),fingerprint:text("fingerprint").notNull(),number:text("number").notNull(),customerName:text("customer_name").notNull(),email:text("email").notNull(),phone:text("phone").notNull(),vehicle:text("vehicle").notNull(),note:text("note").notNull(),itemsJson:text("items_json").notNull(),totalCents:integer("total_cents").notNull(),status:text("status").notNull().default("NEW"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull(),revision:integer("revision").notNull().default(0),
 inventoryMode:text("inventory_mode").notNull().default("standalone"),inventoryStatus:text("inventory_status").notNull().default("LOCAL"),erpRevision:integer("erp_revision").notNull().default(0),reservationExpiresAt:text("reservation_expires_at"),approvedBy:text("approved_by"),approvedAt:text("approved_at"),approvalKey:text("approval_key"),
},t=>[uniqueIndex("commerce_order_idempotency").on(t.owner,t.store,t.idempotency),uniqueIndex("commerce_approval_key").on(t.owner,t.store,t.approvalKey),index("commerce_orders_owner_date").on(t.owner,t.store,t.createdAt)]);
export const events=sqliteTable("commerce_order_events",{id:text("id").primaryKey(),owner:text("owner").notNull(),store:text("store").notNull(),orderId:text("order_id").notNull(),status:text("status").notNull(),createdAt:text("created_at").notNull(),actor:text("actor"),detail:text("detail")},t=>[index("commerce_events_order").on(t.owner,t.store,t.orderId)]);
export const settings=sqliteTable("commerce_settings",{owner:text("owner").notNull(),store:text("store").notNull(),erpAccessEnabled:integer("erp_access_enabled").notNull().default(0),stockIntegrationEnabled:integer("stock_integration_enabled").notNull().default(0)},t=>[primaryKey({columns:[t.owner,t.store]})]);
export const inventoryJobs=sqliteTable("commerce_inventory_jobs",{
 id:text("id").primaryKey(),owner:text("owner").notNull(),store:text("store").notNull(),orderId:text("order_id").notNull(),localRevision:integer("local_revision").notNull(),action:text("action").notNull(),payload:text("payload").notNull(),state:text("state").notNull().default("PENDING"),attempts:integer("attempts").notNull().default(0),lastError:text("last_error"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull(),
},t=>[uniqueIndex("commerce_inventory_job_revision").on(t.owner,t.store,t.orderId,t.localRevision),index("commerce_inventory_pending").on(t.owner,t.store,t.state,t.createdAt)]);
